const GET_USER = 'Redux/GET_USER';

export {GET_USER};

const GET_USER_INFO = 'Redux/GET_USER_INFO';

export {GET_USER_INFO};


const CLEAR_STORAGE = 'Redux/CLEAR_STORAGE';

export {CLEAR_STORAGE};
const CLEAR_STORAGE_REQUIRED = 'Redux/CLEAR_STORAGE_REQUIRED';

export {CLEAR_STORAGE_REQUIRED};